const Types = {
  ADD_TODO_ITEM:      'ADD_TODO_ITEM',
  TOGGLE_TODO_ITEM:   'TOGGLE_TODO_ITEM',
  REMOVE_TODO_ITEM:   'REMOVE_TODO_ITEM',
  SET_ACTIVE_FILTER:  'SET_ACTIVE_FILTER'
}

export default Types;